### ISSUE TITLE
Getting React Error

### ISSUE THREAD

**Issue by vivekdhiman** [Adobe-Marketing-Cloud/aem-guides-wknd-events#17]
Hi,

While using SPA, I am facing below problem. Due to this components are not rendering properly.

![image](https://user-images.githubusercontent.com/7066652/47737966-234a1f00-dc98-11e8-9681-b9b6c5c9a5fd.png)

**Comment by godanny86** [comment]
Hi @vivekdhiman,

A few questions:
1. What version of AEM? Is it 6.4 + SP2?
2. What chapter/version of the app are you running?
3. What happens when you view `/content/wknd-events/react.model.json` in the browser?

**Comment by vivekdhiman** [comment]
Closing this issue as problem solved after installing SP2

**Comment by sambasivaraja** [comment]
Hi ,
Am running on 6.4 with SP2 installed . When I tried to debug the issue better , I could find a smilar thread as mentioned below . On page load "react.model.json" is invoked but instead of JSON response it does 302 to login . That is the main reason for getting JSON exception .Details information as follow .

https://forums.adobe.com/thread/2548513

![sp2](https://user-images.githubusercontent.com/23374164/47986182-573c9e80-e0f5-11e8-99e1-6afec03a5607.PNG)

Trying to get the sample SPA app (we.retail.journal) running. I face an issue with the react.model.json

 The cookie is not passed in the request, so i get redirected to the logging page.

This prevents the site being properly loaded.

 Below you find the headers.

 General:

Request URL: http://localhost:4502/content/we-retail-journal/react.model.json
Request Method: GET
Status Code: 302 Found
Remote Address: [::1]:4502
Referrer Policy: no-referrer-when-downgrade
Request Header:

Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: no-cache
Connection: keep-alive
Host: localhost:4502
Pragma: no-cache
Referer: http://localhost:4502/content/we-retail-journal/react.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
Response Header:

HTTP/1.1 302 Found Date: Wed, 17 Oct 2018 11:43:27 GMT Location: http://localhost:4502/libs/granite/core/content/login.html?resource=%2Fcontent%2Fwe-retail -journal%2Freact.model.json&$$login$$=%24%24login%24%24&j_reason=unknown&j_reason_code=unk nown Content-Length: 0

**Comment by godanny86** [comment]
hi @sambasivaraja, I have to admit I have not seen this behavior before. You are logged into the AEM instance as admin? i.e you can hit  http://localhost:4502/content/we-retail-journal/react.html without being forced to login?

Also, this shouldn't matter, but what browser are you using?

**Comment by SeanAntony** [comment]
Hi @godanny86 

I was going to open a new bug for the following, but my issue might be similar. Please see 
![error1](https://user-images.githubusercontent.com/14054963/49602232-f6072580-f955-11e8-8962-3e1747de34dc.png)

I get that error when I click on the enrollment link, while running the react app on localhost:3000.

If I run the same app on my local AEM instance, I get the following error, which is similar to @vivekdhiman original post. 
<img width="896" alt="error2" src="https://user-images.githubusercontent.com/14054963/49602444-7d549900-f956-11e8-8ca3-6d0977522b09.png">

Both of the images is using the list component from chapter 3.
